---
micronaut:
  application:
    name: conferenceservice
  server:
    port: 8090

---
datasources.default: { }
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

---
micronaut:
  http:
    client:
      read-timeout: 8s

---
micronaut:
  http:
    services:
      presentationservice:
        urls:
          - http://localhost:8081/
        read-timeout: 3s